### ISSUE TITLE
Hi, I would like to ask some questions about the data

### ISSUE THREAD

**Issue by lixingang** [rknaebel/landslide#1]
Hello, I am currently working on landslide related projects. Could you please inform us about the source of the landslide image data? Thank you very much !

**Comment by rknaebel** [comment]
Hi @lixingang 
the date was provided by the a geography research institute in germany.
The data came in geotiff format having 5 spectral bands (blue, green, red, RedEdge, NIR).
In addition i ve got NDVI information (normalized difference vegetation index) and hand annotated masks for occurrences of landslides.

**Comment by MVPTylerE** [comment]
Hello, how about your thesis now? Can you send me your some publications about this work? Thank you very much!

**Comment by rknaebel** [comment]
Unfortunately, I cannot send you this thesis @MVPTylerE because after a few months I have changed the topic and did not finish this project.
